config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/callbacks" }
  devise_scope :user do
    authenticated :user do
      delete 'sign_out', :to => 'devise/sessions#destroy'
      root "projects#index", as: :authenticated_root
      resources :users
      resources :projects, only: [:index]
      resources :tasks, only: [:index]
      resources :chatrooms, param: :slug
      resources :messages
    end
    unauthenticated :user do
      match '/sessions/user', to: 'devise/sessions#create', via: :post
      root "static_pages#index", as: :unauthenticated_root
    end
  end

  resources :users
  resources :projects, only: [:index]
  resources :tasks, only: [:index]
  resources :chatrooms, param: :slug
  resources :messages



  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :projects, only: [:index, :create, :destroy, :update]
      resources :tasks, only: [:index, :create, :destroy, :show, :update]
      resources :users, only: [:index]
    end
  end

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :users, through: :messages
  has_many :userchatrooms
  has_many :users, through: :userchatrooms
  validates :topic, presence: true, uniqueness: true, case_sensitive: false
  before_validation :sanitize, :slugify

  def to_param
    self.slug
  end

  def slugify
    self.slug = self.topic.downcase.gsub(" ", "-")
  end

  def sanitize
    self.topic = self.topic.strip
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @chatroom = Chatroom.new
    @chatrooms = current_user.chatrooms
    @public_rooms = []
    all_chatrooms = Chatroom.all
    all_chatrooms.each do |chatroom|
      if chatroom.public
        @public_rooms.push(chatroom)
      end
    end
  end

  def new
    if request.referrer.split("/").last == "chatrooms"
      flash[:notice] = nil
    end
    @chatroom = Chatroom.new
  end

  def edit
    @chatroom = Chatroom.find_by(slug: params[:slug])
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      admin = Role.find_by(name: "admin")
      Userchatroom.create(user: current_user, chatroom: @chatroom, role: admin)
      respond_to do |format|
        format.html { redirect_to @chatroom }
        format.js
      end
    else
      respond_to do |format|
        flash[:notice] = {error: ["a chatroom with this topic already exists"]}
        format.html { redirect_to new_chatroom_path }
        format.js { render template: 'chatrooms/chatroom_error.js.erb'}
      end
    end
  end

  def update
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @chatroom.update(chatroom_params)
    if @chatroom.save
      add_users = params[:user][:username]
      add_users.each do |user|
        participant = User.find_by(username: user)
        Userchatroom.create(user: participant, chatroom: @chatroom, role: Role.find_by(name: 'member')) unless participant.nil?
      end
    end
    redirect_to chatrooms_path
  end

  def show
    @chatrooms = current_user.chatrooms
    @public_rooms = []
    all_chatrooms = Chatroom.all
    all_chatrooms.each do |chatroom|
      if chatroom.public
        @public_rooms.push(chatroom)
      end
    end
    @chatroom = Chatroom.find_by(slug: params[:slug])
    @message = Message.new
    @users = User.all
    @verified = false
    @userchatrooms = Userchatroom.where(chatroom: @chatroom)
    @userchatrooms.each do |room|
      if room.role.name == 'admin'
        @admin = room.user
      end
      if room.role.name == 'admin' && room.user == current_user
        @verified = true
      end
    end
  end

  private
    def chatroom_params
      params.require(:chatroom).permit(:topic, :public)
    end
end

app/views/chatrooms/_chatroom.html.erb
<li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>

app/views/chatrooms/_chatroom_edit.html.erb
<div id="edit_chatroom_modal" class="modal">
  <div class="modal-content">
    <div class="row header teal lighten-2">
      <h4 class="col s8 offset-s2"><i class="material-icons">settings</i> Chatroom Settings</h4>
    </div>
    <%= form_for @chatroom, remote: true, authenticity_token: true, html: { method: :put }, id: 'edit_chatroom', class: 'col s8 offset-s2' do |f| %>
      <div class="row">
        <span class="topic label col s2">Topic </span>
        <div class="input-field inline col s9">
          <%= f.text_field :topic, id: 'topic', class: 'validate' %>
        </div>
      </div>
      <% if @verified %>
        <div class="row privacy">
          <span class="label col s2">Privacy</span>
          <div class="col s9">
            <%= f.radio_button(:public, true) %>
            <%= f.label(:public_true, "Public") %><br />
            <%= f.radio_button(:public, false) %>
            <%= f.label(:public_false, "Private") %>
          </div>
        </div>
      <% end %>
      <% if !@chatroom.public %>
        <div class="row" id="invite_users">
          <span class="label invite col s2">Invite Users</span>
          <div class="input-field col s6">
            <% users_arr = @users.map { |user| [user.username, user.username] unless user == current_user }.compact %>
            <%= select_tag "user[username][]", options_for_select(users_arr), multiple: true %>
          </div>
        </div>
      <% end %>
      <div class="row button">
        <%= f.submit 'Save', class: 'modal-action modal-close wave-green btn-flat col s2 offset-s9', id: 'chatroomEdit_button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/chatrooms/_chatroom_form.html.erb
<div class="col s6 offset-s1" id="new-chatroom">
  <%= form_for chatroom do |f| %>
    <div class="new-topic">
      <div class="input-field topic">
        <i class="material-icons prefix">group_add</i>
        <%= f.text_field :topic, class: "form-control validate", id: "icon_prefix" %>
        <label for="icon_prefix">Start a topic</label>
      </div>
      <div class="chatroom-button">
        <%= f.submit 'Create', class: "btn waves-effect waves-light", id: "create-chatroom", class: 'submit-button' %>
      </div>
    </div>
  <% end %>
</div>

app/views/chatrooms/_chatroom_members.html.erb
<div id="chatroom_members_modal" class="modal">
  <div class="modal-content">
    <div class="row header teal lighten-2">
      <h4 class="col s8 offset-s2"><i class="material-icons">group</i> <%= @chatroom.topic %> Members</h4>
    </div>
    <div class="row">
      <ul class="list-users col s6 offset-s3">
        <% @userchatrooms.each do |room| %>
          <% if room.user == current_user %>
            <li><span class="teal-text">You</span> (<%= current_user.username %>)</li>
          <% else %>
            <% if room.user != @admin %>
              <li><%= room.user.username %></li>
            <% else %>
              <li><span class="deep-orange-text"><%= @admin.username %></span> (admin)</li>
            <% end %>
          <% end %>
        <% end %>

      </ul>
    </div>

  </div>
</div>

app/views/chatrooms/index.html.erb
<div id="chatrooms">
  <div class="row section">
    <h3 class="col s4"><span class="word deep-orange-text">Create</span> a Chatroom</h3>
    <%= render partial: 'chatroom_form', locals: {chatroom: @chatroom} %>
    <div id="chatroom-errors">
    </div>
  </div>

<div class="row section">
  <h3 class="col s4"><span class="word deep-orange-text">Join</span> a Chatroom</h3>
  <div class="collection chatroom-list col s6 offset-s1">
    <% if @chatrooms.any? %>
      <% @chatrooms.each do |chatroom| %>
        <%= link_to chatroom.topic, chatroom_path(chatroom), class: "collection-item" %>
      <% end %>
    <% else %>
      <p>Be the first one to make a chatroom!</p>
    <% end %>
    <% if @public_rooms.any? %>
      <% @public_rooms.each do |room| %>
        <% unless current_user.chatrooms.include?(room) %>
        <%= link_to room.topic, chatroom_path(room), class: "collection-item" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/chatrooms/show.html.erb
<div id="chatroom_show">
  <div class="header">
    <h2><%= @chatroom.topic %></h2>

    <div class="options">
      <div class="chatroom-members">
        <a class="user-modal" href="#chatroom_members_modal"><i class="material-icons">group</i>Users</a>
        <%= render 'chatrooms/chatroom_members' %>
      </div>
    <div class="chatroom-edit">
      <a class="edit-modal" href="#edit_chatroom_modal"><i class="material-icons">settings</i>Settings</a>
      <%= render 'chatrooms/chatroom_edit' %>
    </div>

    <div class="chatroom-dropdown">
      <a class='dropdown-button' href='#' data-activates='list-chatrooms'><i class="material-icons">list</i>Chatrooms</a>
      <ul id='list-chatrooms' class='dropdown-content'>
        <% @chatrooms.each do |chatroom| %>
          <% if chatroom != @chatroom %>
            <li><%= link_to chatroom.topic, chatroom_path(chatroom) %></li>
          <% end %>
        <% end %>
        <% @public_rooms.each do |room| %>
          <% unless room == @chatroom || current_user.chatrooms.include?(room) %>
            <li><%= link_to room.topic, chatroom_path(room) %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  </div>

  <div class="row">
    <div class="panel panel-default">
      <% if @chatroom.messages.any? %>
        <div class="panel-body" id="messages">
          <%= render partial: 'messages/message', collection: @chatroom.messages%>
        </div>
      <%else%>
        <div class="panel-body hidden" id="messages">
        </div>
      <%end%>
    </div>

    <%= render partial: 'messages/message_form', locals: {message: @message, chatroom: @chatroom}%>
  </div>


</div>