config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/callbacks" }
  devise_scope :user do
    authenticated :user do
      delete 'sign_out', :to => 'devise/sessions#destroy'
      root "projects#index", as: :authenticated_root
      resources :users
      resources :projects, only: [:index]
      resources :tasks, only: [:index]
      resources :chatrooms, param: :slug
      resources :messages
    end
    unauthenticated :user do
      match '/sessions/user', to: 'devise/sessions#create', via: :post
      root "static_pages#index", as: :unauthenticated_root
    end
  end

  resources :users
  resources :projects, only: [:index]
  resources :tasks, only: [:index]
  resources :chatrooms, param: :slug
  resources :messages



  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  namespace :api do
    namespace :v1 do
      resources :projects, only: [:index, :create, :destroy, :update]
      resources :tasks, only: [:index, :create, :destroy, :show, :update]
      resources :users, only: [:index]
    end
  end

end

app/views/layouts/_navbar.html.erb
<nav>
  <div class="nav-wrapper blue-grey white-text">
    <a href="#" class="brand-logo">My<span class="deep-orange-text">Tasky</span><span class="small-caps">friend</span></a>
    <a href="#" data-activates="mobile-demo" class="button-collapse">
      <i class="fa fa-bars"></i></a>
    <ul class="right hide-on-med-and-down">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "Chatrooms", chatrooms_path %>
      <% if user_signed_in? %>
        <li>
        <%= link_to current_user.username, current_user, { style: 'inline' } %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
    </ul>

    <ul class="side-nav" id="mobile-demo">
      <li><%= link_to "Projects", projects_path %></li>
      <li><%= link_to "Chatrooms", chatrooms_path %>
        <% if user_signed_in? %>
          <li>
          <%= link_to current_user.username, current_user, { style: 'inline' } %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mytaskyfriend</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div id="flash">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>
  </body>
</html>